import { EtfHolding } from "@/lib/types";

// Approximate top holdings for each sector/thematic ETF tracked in
// lib/mock-data/indices.ts (region: "sectors") — used by the
// sector-heatmap drilldown (components/dashboard/tools/SectorHeatmapModal.tsx)
// opened when the user clicks a sector tile in WatchedIndicesCard.
// Weights are illustrative approximations of each real ETF's actual
// concentration pattern (not live holdings data), and dayChangePct is
// mock, loosely centered around that ETF's own daily return in
// mockIndices so the heatmap "hangs together" with the tile it was
// opened from. Phase 3 would replace this with a live ETF-holdings feed.
export const mockEtfHoldings: Record<string, EtfHolding[]> = {
  xlk: [
    { ticker: "AAPL", nameHe: "אפל", weightPct: 21.8, dayChangePct: 0.6 },
    { ticker: "NVDA", nameHe: "אנבידיה", weightPct: 20.4, dayChangePct: 2.1 },
    { ticker: "MSFT", nameHe: "מיקרוסופט", weightPct: 12.6, dayChangePct: 1.2 },
    { ticker: "AVGO", nameHe: "ברודקום", weightPct: 5.1, dayChangePct: 1.8 },
    { ticker: "ORCL", nameHe: "אורקל", weightPct: 3.4, dayChangePct: 0.4 },
    { ticker: "CRM", nameHe: "סיילספורס", weightPct: 2.6, dayChangePct: -0.3 },
    { ticker: "PLTR", nameHe: "פלנטיר", weightPct: 2.3, dayChangePct: 3.6 },
    { ticker: "CSCO", nameHe: "סיסקו", weightPct: 2.1, dayChangePct: 0.2 },
    { ticker: "ACN", nameHe: "אקסנצ׳ר", weightPct: 1.9, dayChangePct: -0.5 },
    { ticker: "AMD", nameHe: "AMD", weightPct: 1.8, dayChangePct: 2.4 },
  ],
  xlf: [
    { ticker: "BRK.B", nameHe: "ברקשייר הת'אווי", weightPct: 12.9, dayChangePct: 0.2 },
    { ticker: "JPM", nameHe: "ג׳יי.פי מורגן", weightPct: 9.1, dayChangePct: 0.5 },
    { ticker: "V", nameHe: "ויזה", weightPct: 6.8, dayChangePct: 0.3 },
    { ticker: "MA", nameHe: "מאסטרקארד", weightPct: 5.9, dayChangePct: 0.4 },
    { ticker: "BAC", nameHe: "בנק אוף אמריקה", weightPct: 4.2, dayChangePct: 0.6 },
    { ticker: "WFC", nameHe: "וולס פארגו", weightPct: 3.5, dayChangePct: 0.1 },
    { ticker: "GS", nameHe: "גולדמן זאקס", weightPct: 3.1, dayChangePct: 0.7 },
    { ticker: "SPGI", nameHe: "S&P Global", weightPct: 2.4, dayChangePct: -0.2 },
    { ticker: "AXP", nameHe: "אמריקן אקספרס", weightPct: 2.2, dayChangePct: 0.3 },
    { ticker: "MS", nameHe: "מורגן סטנלי", weightPct: 2.0, dayChangePct: 0.5 },
  ],
  xlv: [
    { ticker: "LLY", nameHe: "אלי לילי", weightPct: 12.4, dayChangePct: -0.4 },
    { ticker: "UNH", nameHe: "יונייטד הלת׳", weightPct: 8.7, dayChangePct: -0.8 },
    { ticker: "JNJ", nameHe: "ג׳ונסון אנד ג׳ונסון", weightPct: 6.9, dayChangePct: 0.1 },
    { ticker: "ABBV", nameHe: "אבווי", weightPct: 5.8, dayChangePct: -0.2 },
    { ticker: "MRK", nameHe: "מרק", weightPct: 4.3, dayChangePct: -0.6 },
    { ticker: "TMO", nameHe: "תרמו פישר", weightPct: 3.6, dayChangePct: 0.2 },
    { ticker: "ABT", nameHe: "אבוט", weightPct: 3.2, dayChangePct: 0.1 },
    { ticker: "PFE", nameHe: "פייזר", weightPct: 2.4, dayChangePct: -0.5 },
    { ticker: "ISRG", nameHe: "אינטואיטיב סרג׳יקל", weightPct: 2.3, dayChangePct: 0.8 },
    { ticker: "DHR", nameHe: "דנהר", weightPct: 2.1, dayChangePct: 0.0 },
  ],
  xle: [
    { ticker: "XOM", nameHe: "אקסון מוביל", weightPct: 22.6, dayChangePct: 0.7 },
    { ticker: "CVX", nameHe: "שברון", weightPct: 15.8, dayChangePct: 0.5 },
    { ticker: "COP", nameHe: "קונוקופיליפס", weightPct: 6.4, dayChangePct: 0.3 },
    { ticker: "WMB", nameHe: "וויליאמס קומפניז", weightPct: 4.1, dayChangePct: 0.9 },
    { ticker: "EOG", nameHe: "EOG Resources", weightPct: 3.8, dayChangePct: 0.4 },
    { ticker: "SLB", nameHe: "שלומברז׳ה", weightPct: 3.2, dayChangePct: -0.3 },
    { ticker: "MPC", nameHe: "מרתון פטרוליום", weightPct: 2.9, dayChangePct: 0.6 },
    { ticker: "PSX", nameHe: "פיליפס 66", weightPct: 2.6, dayChangePct: 0.2 },
    { ticker: "OXY", nameHe: "אוקסידנטל פטרוליום", weightPct: 2.3, dayChangePct: -0.1 },
    { ticker: "KMI", nameHe: "קינדר מורגן", weightPct: 2.0, dayChangePct: 0.8 },
  ],
  xli: [
    { ticker: "GE", nameHe: "ג׳נרל אלקטריק", weightPct: 5.6, dayChangePct: 0.5 },
    { ticker: "RTX", nameHe: "RTX קורפ׳", weightPct: 4.8, dayChangePct: 0.3 },
    { ticker: "CAT", nameHe: "קטרפילר", weightPct: 4.4, dayChangePct: 0.4 },
    { ticker: "UBER", nameHe: "אובר", weightPct: 4.1, dayChangePct: 1.2 },
    { ticker: "HON", nameHe: "הנייוול", weightPct: 3.6, dayChangePct: 0.1 },
    { ticker: "UNP", nameHe: "יוניון פסיפיק", weightPct: 3.2, dayChangePct: 0.2 },
    { ticker: "ADP", nameHe: "ADP", weightPct: 2.8, dayChangePct: 0.0 },
    { ticker: "BA", nameHe: "בואינג", weightPct: 2.6, dayChangePct: -0.9 },
    { ticker: "ETN", nameHe: "איטון קורפ׳", weightPct: 2.4, dayChangePct: 0.6 },
    { ticker: "LMT", nameHe: "לוקהיד מרטין", weightPct: 2.2, dayChangePct: -0.2 },
  ],
  xly: [
    { ticker: "AMZN", nameHe: "אמזון", weightPct: 23.4, dayChangePct: 1.1 },
    { ticker: "TSLA", nameHe: "טסלה", weightPct: 13.6, dayChangePct: 2.3 },
    { ticker: "HD", nameHe: "הום דיפו", weightPct: 6.8, dayChangePct: 0.3 },
    { ticker: "MCD", nameHe: "מקדונלד'ס", weightPct: 4.2, dayChangePct: -0.1 },
    { ticker: "BKNG", nameHe: "בוקינג הולדינגס", weightPct: 3.6, dayChangePct: 0.6 },
    { ticker: "LOW", nameHe: "לואוס", weightPct: 2.9, dayChangePct: 0.2 },
    { ticker: "TJX", nameHe: "TJX קומפניז", weightPct: 2.4, dayChangePct: 0.4 },
    { ticker: "SBUX", nameHe: "סטארבקס", weightPct: 2.1, dayChangePct: -0.5 },
    { ticker: "NKE", nameHe: "נייקי", weightPct: 1.9, dayChangePct: -0.3 },
    { ticker: "CMG", nameHe: "צ׳יפוטלה", weightPct: 1.7, dayChangePct: 0.7 },
  ],
  xlp: [
    { ticker: "PG", nameHe: "פרוקטר אנד גמבל", weightPct: 13.8, dayChangePct: -0.1 },
    { ticker: "COST", nameHe: "קוסטקו", weightPct: 11.2, dayChangePct: 0.3 },
    { ticker: "WMT", nameHe: "וולמארט", weightPct: 9.6, dayChangePct: 0.2 },
    { ticker: "KO", nameHe: "קוקה קולה", weightPct: 8.4, dayChangePct: 0.0 },
    { ticker: "PM", nameHe: "פיליפ מוריס", weightPct: 5.6, dayChangePct: 0.1 },
    { ticker: "PEP", nameHe: "פפסיקו", weightPct: 5.1, dayChangePct: -0.2 },
    { ticker: "MO", nameHe: "אלטריה", weightPct: 3.2, dayChangePct: 0.1 },
    { ticker: "CL", nameHe: "קולגייט-פלמוליב", weightPct: 2.6, dayChangePct: -0.1 },
    { ticker: "MDLZ", nameHe: "מונדליז", weightPct: 2.4, dayChangePct: 0.2 },
    { ticker: "TGT", nameHe: "טארגט", weightPct: 1.8, dayChangePct: -0.6 },
  ],
  xlu: [
    { ticker: "NEE", nameHe: "נקסטרה אנרג'י", weightPct: 11.6, dayChangePct: 0.3 },
    { ticker: "SO", nameHe: "סאתרן קומפני", weightPct: 7.4, dayChangePct: 0.1 },
    { ticker: "DUK", nameHe: "דיוק אנרג'י", weightPct: 6.8, dayChangePct: 0.2 },
    { ticker: "CEG", nameHe: "קונסטליישן אנרג'י", weightPct: 5.9, dayChangePct: 0.8 },
    { ticker: "AEP", nameHe: "אמריקן אלקטריק פאוור", weightPct: 4.2, dayChangePct: 0.1 },
    { ticker: "D", nameHe: "דומיניון אנרג'י", weightPct: 3.6, dayChangePct: 0.0 },
    { ticker: "SRE", nameHe: "סמפרה אנרג'י", weightPct: 3.1, dayChangePct: 0.3 },
    { ticker: "EXC", nameHe: "אקסלון", weightPct: 2.8, dayChangePct: -0.1 },
    { ticker: "XEL", nameHe: "אקסל אנרג'י", weightPct: 2.4, dayChangePct: 0.2 },
    { ticker: "ED", nameHe: "קונסולידייטד אדיסון", weightPct: 2.0, dayChangePct: 0.0 },
  ],
  xlb: [
    { ticker: "LIN", nameHe: "ליינדה", weightPct: 19.4, dayChangePct: 0.2 },
    { ticker: "SHW", nameHe: "שרווין-וויליאמס", weightPct: 6.8, dayChangePct: 0.1 },
    { ticker: "FCX", nameHe: "פרימונט מקמורן", weightPct: 5.4, dayChangePct: 1.4 },
    { ticker: "ECL", nameHe: "אקולאב", weightPct: 4.6, dayChangePct: 0.0 },
    { ticker: "NEM", nameHe: "ניומונט", weightPct: 4.1, dayChangePct: 1.8 },
    { ticker: "APD", nameHe: "אייר פרודקטס", weightPct: 3.8, dayChangePct: -0.2 },
    { ticker: "CTVA", nameHe: "קורטבה", weightPct: 3.2, dayChangePct: 0.3 },
    { ticker: "DOW", nameHe: "דאו", weightPct: 2.6, dayChangePct: -0.4 },
    { ticker: "PPG", nameHe: "PPG תעשיות", weightPct: 2.3, dayChangePct: 0.1 },
    { ticker: "VMC", nameHe: "וולקן מטריאלס", weightPct: 2.1, dayChangePct: 0.2 },
  ],
  xlre: [
    { ticker: "PLD", nameHe: "פרולוג'יס", weightPct: 10.8, dayChangePct: -0.1 },
    { ticker: "AMT", nameHe: "אמריקן טאואר", weightPct: 8.4, dayChangePct: 0.2 },
    { ticker: "EQIX", nameHe: "אקוויניקס", weightPct: 6.9, dayChangePct: 0.4 },
    { ticker: "WELL", nameHe: "וולטאואר", weightPct: 5.6, dayChangePct: 0.1 },
    { ticker: "SPG", nameHe: "סיימון פרופרטי", weightPct: 4.8, dayChangePct: -0.3 },
    { ticker: "DLR", nameHe: "דיגיטל ריאלטי", weightPct: 4.1, dayChangePct: 0.3 },
    { ticker: "PSA", nameHe: "פאבליק סטורג'", weightPct: 3.4, dayChangePct: -0.2 },
    { ticker: "O", nameHe: "ריאלטי אינקאם", weightPct: 3.0, dayChangePct: 0.0 },
    { ticker: "CCI", nameHe: "קראון קאסל", weightPct: 2.6, dayChangePct: 0.1 },
    { ticker: "EXR", nameHe: "אקסטרה ספייס", weightPct: 2.3, dayChangePct: -0.1 },
  ],
  xlc: [
    { ticker: "META", nameHe: "מטא", weightPct: 21.6, dayChangePct: 1.4 },
    { ticker: "GOOGL", nameHe: "אלפאבט (A)", weightPct: 12.8, dayChangePct: 0.9 },
    { ticker: "GOOG", nameHe: "אלפאבט (C)", weightPct: 10.9, dayChangePct: 0.9 },
    { ticker: "NFLX", nameHe: "נטפליקס", weightPct: 5.4, dayChangePct: 0.6 },
    { ticker: "TMUS", nameHe: "טי-מובייל", weightPct: 4.6, dayChangePct: 0.2 },
    { ticker: "DIS", nameHe: "וולט דיסני", weightPct: 3.8, dayChangePct: -0.4 },
    { ticker: "VZ", nameHe: "ורייזון", weightPct: 3.1, dayChangePct: 0.0 },
    { ticker: "T", nameHe: "AT&T", weightPct: 2.6, dayChangePct: 0.1 },
    { ticker: "CMCSA", nameHe: "קומקאסט", weightPct: 2.2, dayChangePct: -0.2 },
    { ticker: "EA", nameHe: "אלקטרוניק ארטס", weightPct: 1.4, dayChangePct: 0.5 },
  ],
  igv: [
    { ticker: "MSFT", nameHe: "מיקרוסופט", weightPct: 9.8, dayChangePct: 1.2 },
    { ticker: "CRM", nameHe: "סיילספורס", weightPct: 6.4, dayChangePct: -0.3 },
    { ticker: "ORCL", nameHe: "אורקל", weightPct: 6.1, dayChangePct: 0.4 },
    { ticker: "INTU", nameHe: "אינטואיט", weightPct: 5.8, dayChangePct: 0.6 },
    { ticker: "ADBE", nameHe: "אדובי", weightPct: 5.2, dayChangePct: -0.8 },
    { ticker: "PANW", nameHe: "פאלו אלטו נטוורקס", weightPct: 4.9, dayChangePct: 1.1 },
    { ticker: "NOW", nameHe: "סרוויסנאו", weightPct: 4.6, dayChangePct: 0.7 },
    { ticker: "SNPS", nameHe: "סינופסיס", weightPct: 4.1, dayChangePct: 0.3 },
    { ticker: "CDNS", nameHe: "קדנס דיזיין", weightPct: 3.8, dayChangePct: 0.5 },
    { ticker: "WDAY", nameHe: "וורקדיי", weightPct: 3.2, dayChangePct: -0.4 },
  ],
  cibr: [
    { ticker: "PANW", nameHe: "פאלו אלטו נטוורקס", weightPct: 8.9, dayChangePct: 1.3 },
    { ticker: "CRWD", nameHe: "קראודסטרייק", weightPct: 8.2, dayChangePct: 2.1 },
    { ticker: "FTNT", nameHe: "פורטינט", weightPct: 6.8, dayChangePct: 0.6 },
    { ticker: "PLTR", nameHe: "פלנטיר", weightPct: 5.4, dayChangePct: 3.6 },
    { ticker: "ZS", nameHe: "זסקיילר", weightPct: 4.9, dayChangePct: 1.8 },
    { ticker: "CSCO", nameHe: "סיסקו", weightPct: 4.2, dayChangePct: 0.2 },
    { ticker: "OKTA", nameHe: "אוקטה", weightPct: 3.6, dayChangePct: -0.5 },
    { ticker: "CHKP", nameHe: "צ׳ק פוינט", weightPct: 3.1, dayChangePct: 0.4 },
    { ticker: "S", nameHe: "סנטינל וואן", weightPct: 2.8, dayChangePct: 2.4 },
    { ticker: "GEN", nameHe: "ג'ן דיגיטל", weightPct: 2.4, dayChangePct: 0.1 },
  ],
  soxx: [
    { ticker: "NVDA", nameHe: "אנבידיה", weightPct: 9.4, dayChangePct: 2.1 },
    { ticker: "AVGO", nameHe: "ברודקום", weightPct: 8.6, dayChangePct: 1.8 },
    { ticker: "AMD", nameHe: "AMD", weightPct: 6.2, dayChangePct: 2.4 },
    { ticker: "QCOM", nameHe: "קוואלקום", weightPct: 5.4, dayChangePct: 0.9 },
    { ticker: "TXN", nameHe: "טקסס אינסטרומנטס", weightPct: 4.8, dayChangePct: 0.3 },
    { ticker: "INTC", nameHe: "אינטל", weightPct: 4.1, dayChangePct: -1.2 },
    { ticker: "AMAT", nameHe: "אפלייד מטיריאלס", weightPct: 3.9, dayChangePct: 1.4 },
    { ticker: "LRCX", nameHe: "לאם ריסרץ'", weightPct: 3.6, dayChangePct: 1.6 },
    { ticker: "TSM", nameHe: "טאיוואן סמיקונדקטור", weightPct: 3.4, dayChangePct: 1.1 },
    { ticker: "KLAC", nameHe: "KLA קורפ׳", weightPct: 3.1, dayChangePct: 0.8 },
  ],
  aiq: [
    { ticker: "NVDA", nameHe: "אנבידיה", weightPct: 8.6, dayChangePct: 2.1 },
    { ticker: "MSFT", nameHe: "מיקרוסופט", weightPct: 7.4, dayChangePct: 1.2 },
    { ticker: "GOOGL", nameHe: "אלפאבט", weightPct: 6.8, dayChangePct: 0.9 },
    { ticker: "META", nameHe: "מטא", weightPct: 6.1, dayChangePct: 1.4 },
    { ticker: "PLTR", nameHe: "פלנטיר", weightPct: 5.6, dayChangePct: 3.6 },
    { ticker: "AMD", nameHe: "AMD", weightPct: 4.8, dayChangePct: 2.4 },
    { ticker: "CRM", nameHe: "סיילספורס", weightPct: 3.9, dayChangePct: -0.3 },
    { ticker: "SNOW", nameHe: "סנואופלייק", weightPct: 3.4, dayChangePct: 1.9 },
    { ticker: "AMZN", nameHe: "אמזון", weightPct: 3.1, dayChangePct: 1.1 },
    { ticker: "IBM", nameHe: "IBM", weightPct: 2.6, dayChangePct: 0.2 },
  ],
  dram: [
    { ticker: "MU", nameHe: "מייקרון טכנולוג'י", weightPct: 14.8, dayChangePct: 3.1 },
    { ticker: "NVDA", nameHe: "אנבידיה", weightPct: 11.2, dayChangePct: 2.1 },
    { ticker: "WDC", nameHe: "וסטרן דיגיטל", weightPct: 8.6, dayChangePct: 2.6 },
    { ticker: "STX", nameHe: "סיגייט טכנולוג'י", weightPct: 7.4, dayChangePct: 2.2 },
    { ticker: "LRCX", nameHe: "לאם ריסרץ'", weightPct: 6.1, dayChangePct: 1.6 },
    { ticker: "AMAT", nameHe: "אפלייד מטיריאלס", weightPct: 5.4, dayChangePct: 1.4 },
    { ticker: "KLAC", nameHe: "KLA קורפ׳", weightPct: 4.6, dayChangePct: 0.8 },
    { ticker: "ONTO", nameHe: "אונטו אינובישן", weightPct: 3.2, dayChangePct: 1.1 },
  ],
};
