import { IndexCategoryOption, IndexPeriodOption, IndexQuote } from "@/lib/types";

// Periods selectable for the watched-indices card.
export const indexPeriodOptions: IndexPeriodOption[] = [
  { id: "daily", labelHe: "יומי" },
  { id: "weekly", labelHe: "שבועי" },
  { id: "quarterly", labelHe: "רבעוני" },
  { id: "ytd", labelHe: "מתחילת שנה" },
  { id: "yearly", labelHe: "שנתי" },
  { id: "5y", labelHe: "5 שנים" },
];

// Category tabs for the watched-indices card. "main" keeps the original
// Israel/US split; the rest switch to a single grid of ETFs/yields/
// commodities for that group.
export const indexCategoryOptions: IndexCategoryOption[] = [
  { id: "main", labelHe: 'ישראל וארה"ב' },
  { id: "sectors", labelHe: "סקטורים" },
  { id: "asia", labelHe: "אסיה" },
  { id: "south-america", labelHe: "דרום אמריקה" },
  { id: "europe", labelHe: "אירופה" },
  { id: "bonds", labelHe: 'אג"ח' },
  { id: "commodities", labelHe: "סחורות" },
];

// Watchlist of indices/ETFs shown alongside the portfolio, independent of
// what the user actually holds, with a return for every selectable
// period. Mock quotes for Phase 1/2; Phase 3 will refresh these from a
// live market-data API.
export const mockIndices: IndexQuote[] = [
  // --- Israel ---
  {
    id: "ta35",
    labelHe: 'ת"א 35',
    valuePts: 2148.3,
    region: "il",
    peRatio: 13.5,
    forwardPeRatio: 12.2,
    returns: { daily: 0.4, weekly: 0.9, quarterly: 4.8, ytd: 11.4, yearly: 15.7, "5y": 61.2 },
  },
  {
    id: "ta125",
    labelHe: 'ת"א 125',
    valuePts: 2384.1,
    region: "il",
    peRatio: 14.2,
    forwardPeRatio: 12.8,
    returns: { daily: 0.3, weekly: 0.7, quarterly: 5.2, ytd: 12.6, yearly: 16.9, "5y": 66.4 },
  },
  {
    id: "ta-tech",
    labelHe: 'ת"א טק-עילית',
    valuePts: 412.6,
    region: "il",
    peRatio: 26.4,
    forwardPeRatio: 21.3,
    returns: { daily: 1.1, weekly: 2.0, quarterly: 8.4, ytd: 19.8, yearly: 27.3, "5y": 104.5 },
  },
  // --- Global ---
  {
    id: "sp500",
    labelHe: "S&P 500",
    valuePts: 6482.7,
    region: "global",
    peRatio: 24.8,
    forwardPeRatio: 22.1,
    returns: { daily: 0.6, weekly: 0.9, quarterly: 6.1, ytd: 14.8, yearly: 19.4, "5y": 92.8 },
  },
  {
    id: "nasdaq100",
    labelHe: "Nasdaq 100",
    valuePts: 22_845.2,
    region: "global",
    peRatio: 32.6,
    forwardPeRatio: 27.4,
    returns: { daily: 0.9, weekly: 1.1, quarterly: 8.0, ytd: 18.2, yearly: 24.1, "5y": 138.6 },
  },
  {
    id: "vix",
    labelHe: "VIX",
    valuePts: 14.8,
    region: "global",
    returns: { daily: -2.3, weekly: -4.1, quarterly: -8.6, ytd: -12.4, yearly: -18.9, "5y": -35.2 },
  },
  // --- Sector & thematic ETFs (US sector SPDRs + niche ETFs) ---
  {
    id: "xlk",
    labelHe: "XLK — טכנולוגיה",
    valuePts: 254.1,
    region: "sectors",
    peRatio: 29.8,
    forwardPeRatio: 25.6,
    returns: { daily: 1.0, weekly: 1.8, quarterly: 9.4, ytd: 22.6, yearly: 29.8, "5y": 168.3 },
  },
  {
    id: "xlf",
    labelHe: "XLF — פיננסים",
    valuePts: 52.4,
    region: "sectors",
    peRatio: 15.2,
    forwardPeRatio: 13.6,
    returns: { daily: 0.3, weekly: 0.6, quarterly: 5.1, ytd: 13.2, yearly: 18.6, "5y": 78.4 },
  },
  {
    id: "xlv",
    labelHe: "XLV — בריאות",
    valuePts: 148.7,
    region: "sectors",
    peRatio: 17.8,
    forwardPeRatio: 15.9,
    returns: { daily: -0.2, weekly: -0.4, quarterly: 1.8, ytd: 4.6, yearly: 6.1, "5y": 42.7 },
  },
  {
    id: "xle",
    labelHe: "XLE — אנרגיה",
    valuePts: 96.3,
    region: "sectors",
    peRatio: 12.4,
    forwardPeRatio: 11.8,
    returns: { daily: 0.5, weekly: 1.1, quarterly: 3.4, ytd: 8.9, yearly: 11.2, "5y": 89.6 },
  },
  {
    id: "xli",
    labelHe: "XLI — תעשייה",
    valuePts: 142.8,
    region: "sectors",
    peRatio: 21.6,
    forwardPeRatio: 19.4,
    returns: { daily: 0.4, weekly: 0.9, quarterly: 6.2, ytd: 15.4, yearly: 20.3, "5y": 96.1 },
  },
  {
    id: "xly",
    labelHe: "XLY — צריכה מחזורית",
    valuePts: 231.5,
    region: "sectors",
    peRatio: 26.3,
    forwardPeRatio: 22.7,
    returns: { daily: 0.7, weekly: 1.4, quarterly: 7.8, ytd: 17.9, yearly: 23.4, "5y": 112.8 },
  },
  {
    id: "xlp",
    labelHe: "XLP — צריכה בסיסית",
    valuePts: 78.9,
    region: "sectors",
    peRatio: 20.1,
    forwardPeRatio: 18.6,
    returns: { daily: -0.1, weekly: 0.1, quarterly: 1.2, ytd: 3.8, yearly: 5.4, "5y": 34.2 },
  },
  {
    id: "xlu",
    labelHe: "XLU — שירותים ציבוריים",
    valuePts: 84.2,
    region: "sectors",
    peRatio: 18.9,
    forwardPeRatio: 17.2,
    returns: { daily: 0.2, weekly: 0.5, quarterly: 4.1, ytd: 12.7, yearly: 16.8, "5y": 51.3 },
  },
  {
    id: "xlb",
    labelHe: "XLB — חומרי גלם",
    valuePts: 91.6,
    region: "sectors",
    peRatio: 19.4,
    forwardPeRatio: 17.8,
    returns: { daily: 0.3, weekly: 0.6, quarterly: 3.7, ytd: 9.1, yearly: 12.4, "5y": 47.9 },
  },
  {
    id: "xlre",
    labelHe: "XLRE — נדל\"ן",
    valuePts: 43.1,
    region: "sectors",
    peRatio: 35.7,
    forwardPeRatio: 32.1,
    returns: { daily: 0.1, weekly: 0.3, quarterly: 2.4, ytd: 6.8, yearly: 9.7, "5y": 29.6 },
  },
  {
    id: "xlc",
    labelHe: "XLC — תקשורת",
    valuePts: 112.4,
    region: "sectors",
    peRatio: 22.1,
    forwardPeRatio: 19.3,
    returns: { daily: 0.8, weekly: 1.5, quarterly: 8.6, ytd: 20.3, yearly: 27.1, "5y": 134.5 },
  },
  {
    id: "igv",
    labelHe: "IGV — תוכנה (נישה)",
    valuePts: 96.8,
    region: "sectors",
    peRatio: 34.6,
    forwardPeRatio: 28.9,
    returns: { daily: 1.2, weekly: 2.1, quarterly: 10.6, ytd: 24.8, yearly: 31.5, "5y": 142.9 },
  },
  {
    id: "cibr",
    labelHe: "CIBR — סייבר (נישה)",
    valuePts: 68.3,
    region: "sectors",
    peRatio: 38.2,
    forwardPeRatio: 30.4,
    returns: { daily: 1.1, weekly: 2.4, quarterly: 11.9, ytd: 26.3, yearly: 33.7, "5y": 121.4 },
  },
  {
    id: "soxx",
    labelHe: "SOXX — מוליכים למחצה (נישה)",
    valuePts: 254.6,
    region: "sectors",
    peRatio: 28.7,
    forwardPeRatio: 23.1,
    returns: { daily: 1.6, weekly: 3.2, quarterly: 14.8, ytd: 32.1, yearly: 41.6, "5y": 231.7 },
  },
  {
    id: "aiq",
    labelHe: "AIQ — בינה מלאכותית (נישה)",
    valuePts: 42.9,
    region: "sectors",
    peRatio: 41.3,
    forwardPeRatio: 31.8,
    returns: { daily: 1.8, weekly: 3.6, quarterly: 16.4, ytd: 35.9, yearly: 47.2, "5y": 189.3 },
  },
  {
    id: "dram",
    labelHe: "DRAM — שבבי זיכרון (נישה)",
    valuePts: 31.4,
    region: "sectors",
    peRatio: 19.6,
    forwardPeRatio: 14.2,
    returns: { daily: 2.1, weekly: 4.3, quarterly: 19.7, ytd: 41.2, yearly: 55.8, "5y": 176.4 },
  },
  // --- Asia ---
  {
    id: "inda",
    labelHe: "INDA — הודו",
    valuePts: 58.7,
    region: "asia",
    peRatio: 24.6,
    forwardPeRatio: 20.8,
    returns: { daily: 0.4, weekly: 1.0, quarterly: 5.6, ytd: 13.8, yearly: 17.9, "5y": 74.2 },
  },
  {
    id: "nikkei225",
    labelHe: "ניקיי 225 — יפן",
    valuePts: 41_284.6,
    region: "asia",
    peRatio: 19.8,
    forwardPeRatio: 17.6,
    returns: { daily: 0.6, weekly: 1.2, quarterly: 6.9, ytd: 16.4, yearly: 21.8, "5y": 88.6 },
  },
  {
    id: "kospi",
    labelHe: "KOSPI — קוריאה",
    valuePts: 3128.4,
    region: "asia",
    peRatio: 13.4,
    forwardPeRatio: 11.2,
    returns: { daily: 0.9, weekly: 1.8, quarterly: 9.2, ytd: 21.7, yearly: 28.4, "5y": 96.3 },
  },
  {
    id: "eem",
    labelHe: "EEM — שווקים מתעוררים",
    valuePts: 47.6,
    region: "asia",
    peRatio: 15.8,
    forwardPeRatio: 13.6,
    returns: { daily: 0.3, weekly: 0.7, quarterly: 4.9, ytd: 12.1, yearly: 15.6, "5y": 46.8 },
  },
  {
    id: "fxi",
    labelHe: "FXI — סין",
    valuePts: 33.2,
    region: "asia",
    peRatio: 11.2,
    forwardPeRatio: 9.8,
    returns: { daily: 0.5, weekly: 1.4, quarterly: 6.1, ytd: 14.9, yearly: 18.3, "5y": 12.4 },
  },
  {
    id: "ewt",
    labelHe: "EWT — טאיוואן",
    valuePts: 61.9,
    region: "asia",
    peRatio: 19.4,
    forwardPeRatio: 16.7,
    returns: { daily: 1.0, weekly: 2.0, quarterly: 10.4, ytd: 23.6, yearly: 30.1, "5y": 118.7 },
  },
  {
    id: "hsi",
    labelHe: "האנג סנג — הונג קונג",
    valuePts: 21_384.2,
    region: "asia",
    peRatio: 10.6,
    forwardPeRatio: 9.4,
    returns: { daily: 0.4, weekly: 1.1, quarterly: 5.8, ytd: 15.2, yearly: 19.4, "5y": 8.9 },
  },
  {
    id: "vnm",
    labelHe: "VNM — וייטנאם",
    valuePts: 16.8,
    region: "asia",
    peRatio: 13.8,
    forwardPeRatio: 11.9,
    returns: { daily: 0.6, weekly: 1.3, quarterly: 6.7, ytd: 16.8, yearly: 22.1, "5y": 41.3 },
  },
  // --- South America ---
  {
    id: "ewz",
    labelHe: "EWZ — ברזיל",
    valuePts: 34.6,
    region: "south-america",
    peRatio: 9.4,
    forwardPeRatio: 8.1,
    returns: { daily: 0.7, weekly: 1.6, quarterly: 8.3, ytd: 19.4, yearly: 24.7, "5y": 38.9 },
  },
  {
    id: "ech",
    labelHe: "ECH — צ׳ילה",
    valuePts: 28.9,
    region: "south-america",
    peRatio: 14.2,
    forwardPeRatio: 12.6,
    returns: { daily: 0.4, weekly: 0.9, quarterly: 5.2, ytd: 12.6, yearly: 16.4, "5y": 22.7 },
  },
  {
    id: "argt",
    labelHe: "ARGT — ארגנטינה",
    valuePts: 71.3,
    region: "south-america",
    peRatio: 18.7,
    forwardPeRatio: 14.3,
    returns: { daily: 1.4, weekly: 3.1, quarterly: 15.8, ytd: 38.6, yearly: 52.3, "5y": 187.6 },
  },
  {
    id: "gxg",
    labelHe: "GXG — קולומביה",
    valuePts: 24.1,
    region: "south-america",
    peRatio: 10.8,
    forwardPeRatio: 9.6,
    returns: { daily: 0.3, weekly: 0.7, quarterly: 4.6, ytd: 11.3, yearly: 14.8, "5y": 19.4 },
  },
  {
    id: "epu",
    labelHe: "EPU — פרו",
    valuePts: 46.8,
    region: "south-america",
    peRatio: 13.1,
    forwardPeRatio: 11.4,
    returns: { daily: 0.5, weekly: 1.1, quarterly: 6.4, ytd: 15.9, yearly: 20.6, "5y": 31.8 },
  },
  {
    id: "ilf",
    labelHe: "ILF — אמריקה הלטינית (מדד רחב)",
    valuePts: 26.7,
    region: "south-america",
    peRatio: 11.6,
    forwardPeRatio: 10.2,
    returns: { daily: 0.6, weekly: 1.3, quarterly: 7.1, ytd: 17.2, yearly: 22.9, "5y": 34.6 },
  },
  // --- Europe ---
  {
    id: "dax",
    labelHe: "DAX — גרמניה",
    valuePts: 19_842.6,
    region: "europe",
    peRatio: 15.8,
    forwardPeRatio: 14.1,
    returns: { daily: 0.5, weekly: 1.0, quarterly: 6.4, ytd: 15.8, yearly: 20.6, "5y": 79.4 },
  },
  {
    id: "cac40",
    labelHe: "CAC 40 — צרפת",
    valuePts: 7684.2,
    region: "europe",
    peRatio: 16.9,
    forwardPeRatio: 15.2,
    returns: { daily: 0.3, weekly: 0.6, quarterly: 3.9, ytd: 9.7, yearly: 12.8, "5y": 48.6 },
  },
  {
    id: "ftse100",
    labelHe: "FTSE 100 — בריטניה",
    valuePts: 8342.7,
    region: "europe",
    peRatio: 13.6,
    forwardPeRatio: 12.4,
    returns: { daily: 0.2, weekly: 0.5, quarterly: 3.2, ytd: 8.1, yearly: 10.9, "5y": 39.7 },
  },
  {
    id: "eurostoxx50",
    labelHe: "Euro Stoxx 50 — גוש האירו",
    valuePts: 4986.3,
    region: "europe",
    peRatio: 15.2,
    forwardPeRatio: 13.8,
    returns: { daily: 0.4, weekly: 0.8, quarterly: 5.1, ytd: 12.4, yearly: 16.3, "5y": 61.8 },
  },
  {
    id: "ibex35",
    labelHe: "IBEX 35 — ספרד",
    valuePts: 11_824.5,
    region: "europe",
    peRatio: 12.4,
    forwardPeRatio: 11.3,
    returns: { daily: 0.3, weekly: 0.7, quarterly: 4.6, ytd: 13.9, yearly: 18.1, "5y": 55.2 },
  },
  // --- Bond yields (Israel + US) ---
  {
    id: "il-bond-2y",
    labelHe: 'אג"ח ממשלת ישראל 2 שנים',
    valuePts: 3.92,
    region: "bonds",
    returns: { daily: 0.01, weekly: 0.03, quarterly: -0.08, ytd: -0.21, yearly: -0.34, "5y": 1.12 },
  },
  {
    id: "il-bond-10y",
    labelHe: 'אג"ח ממשלת ישראל 10 שנים (גילון)',
    valuePts: 4.68,
    region: "bonds",
    returns: { daily: 0.02, weekly: 0.05, quarterly: -0.12, ytd: -0.28, yearly: -0.41, "5y": 1.34 },
  },
  {
    id: "il-makam",
    labelHe: 'מק"מ 12 חודשים',
    valuePts: 4.21,
    region: "bonds",
    returns: { daily: 0.0, weekly: 0.01, quarterly: -0.06, ytd: -0.18, yearly: -0.29, "5y": 0.87 },
  },
  {
    id: "us-bond-2y",
    labelHe: 'אג"ח ממשלת ארה"ב 2 שנים',
    valuePts: 3.58,
    region: "bonds",
    returns: { daily: -0.01, weekly: -0.04, quarterly: -0.15, ytd: -0.32, yearly: -0.52, "5y": 0.68 },
  },
  {
    id: "us-bond-10y",
    labelHe: 'אג"ח ממשלת ארה"ב 10 שנים (10Y Treasury)',
    valuePts: 4.24,
    region: "bonds",
    returns: { daily: 0.01, weekly: 0.02, quarterly: -0.09, ytd: -0.19, yearly: -0.31, "5y": 0.94 },
  },
  {
    id: "us-bond-30y",
    labelHe: 'אג"ח ממשלת ארה"ב 30 שנה',
    valuePts: 4.51,
    region: "bonds",
    returns: { daily: 0.02, weekly: 0.03, quarterly: -0.05, ytd: -0.11, yearly: -0.18, "5y": 0.76 },
  },
  // --- Commodities ---
  {
    id: "gold",
    labelHe: "זהב (Gold, $/אונקיה)",
    valuePts: 2634.5,
    region: "commodities",
    returns: { daily: 0.4, weekly: 1.1, quarterly: 6.8, ytd: 24.3, yearly: 31.6, "5y": 98.4 },
  },
  {
    id: "silver",
    labelHe: "כסף (Silver, $/אונקיה)",
    valuePts: 30.85,
    region: "commodities",
    returns: { daily: 0.6, weekly: 1.8, quarterly: 9.4, ytd: 32.7, yearly: 41.9, "5y": 112.6 },
  },
  {
    id: "copper",
    labelHe: 'נחושת (Copper, $/ליברה)',
    valuePts: 4.62,
    region: "commodities",
    returns: { daily: 0.3, weekly: 0.9, quarterly: 5.6, ytd: 18.2, yearly: 23.7, "5y": 67.3 },
  },
  {
    id: "wti-oil",
    labelHe: "נפט (WTI, $/חבית)",
    valuePts: 71.3,
    region: "commodities",
    returns: { daily: -0.5, weekly: -1.2, quarterly: 2.1, ytd: -6.4, yearly: -9.8, "5y": 34.6 },
  },
  {
    id: "natgas",
    labelHe: "גז טבעי (Henry Hub, $/MMBtu)",
    valuePts: 2.85,
    region: "commodities",
    returns: { daily: 1.4, weekly: 3.2, quarterly: -8.6, ytd: 14.7, yearly: 19.3, "5y": 22.8 },
  },
  {
    id: "platinum",
    labelHe: "פלטינה (Platinum, $/אונקיה)",
    valuePts: 1045.2,
    region: "commodities",
    returns: { daily: 0.2, weekly: 0.6, quarterly: 3.4, ytd: 9.8, yearly: 12.6, "5y": 28.1 },
  },
];
